export enum TransactionConfirmationState {
  PENDING_LEDGER_CONFIRMATION = 'PENDING_LEDGER_CONFIRMATION',
  PENDING_CONFIRMATION = 'PENDING_CONFIRMATION',
  SUBMITTING = 'SUBMITTING',
  SUCCESS = 'SUCCESS',
  ERROR = 'ERROR',
}
